name: React App Build Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Or your project's Node version

      - name: Install Dependencies
        run: npm install

      - name: Build the Project
        run: npm run build

      - name: Upload Production Build (optional)
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build
