name: Full Stack CI - NODEbook

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Backend setup
      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      # Optional: Run Backend Tests (if you have any)
      - name: Run Backend Tests
        working-directory: backend
        run: npm test
        continue-on-error: true  # Remove this if tests must pass

      # Frontend setup
      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      # Optional: Upload the frontend build as an artifact
      - name: Upload Frontend Build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build
